"""Tests for the MD package builder and /api/md_package endpoint."""

import zipfile
import io

import pytest
from fastapi.testclient import TestClient

from web.app import app
from bilbo.exporters.md_package import build_md_package

client = TestClient(app)

_MINIMAL_PDB = (
    "ATOM      1  CA  ALA A   1       0.000   0.000   0.000  1.00  0.00           C\n"
    "END\n"
)

_MINIMAL_TOP = (
    '; Topology generated by BILBO\n'
    '#include "charmm36.ff/forcefield.itp"\n'
    '; Lipid molecule topologies\n'
    '#include "charmm36.ff/POPE.itp"\n\n'
    '[ system ]\nBILBO Membrane\n\n'
    '[ molecules ]\n; molecule-type  count\nPOPE            32\n'
)

_MINIMAL_PEPTIDE_PDB = (
    "ATOM      1  CA  GLY B   1       5.000   5.000   5.000  1.00  0.00           C\n"
    "END\n"
)


def _open_zip(raw: bytes) -> zipfile.ZipFile:
    return zipfile.ZipFile(io.BytesIO(raw))


# ── unit tests for build_md_package ──────────────────────────────────────────

def test_zip_contains_expected_files_no_peptide():
    raw = build_md_package(_MINIMAL_PDB, _MINIMAL_TOP, solvated=False)
    with _open_zip(raw) as zf:
        names = zf.namelist()
    for f in ("md_package/system.pdb", "md_package/topol.top",
              "md_package/em.mdp", "md_package/nvt.mdp",
              "md_package/npt.mdp", "md_package/prod.mdp",
              "md_package/gmx.sh", "md_package/README.txt"):
        assert f in names, f"missing {f}"
    assert "md_package/peptide.pdb" not in names


def test_zip_contains_peptide_pdb_when_present():
    raw = build_md_package(
        _MINIMAL_PDB, _MINIMAL_TOP,
        has_peptide=True, peptide_pdb_text=_MINIMAL_PEPTIDE_PDB,
    )
    with _open_zip(raw) as zf:
        assert "md_package/peptide.pdb" in zf.namelist()


def test_charmm36_mdp_params_in_em():
    raw = build_md_package(_MINIMAL_PDB, _MINIMAL_TOP)
    with _open_zip(raw) as zf:
        em = zf.read("md_package/em.mdp").decode()
    assert "vdwtype" in em
    assert "force-switch" in em
    assert "rvdw-switch" in em


def test_charmm36_mdp_params_in_npt():
    raw = build_md_package(_MINIMAL_PDB, _MINIMAL_TOP)
    with _open_zip(raw) as zf:
        npt = zf.read("md_package/npt.mdp").decode()
    assert "semiisotropic" in npt
    assert "force-switch" in npt


def test_gmx_sh_has_set_e():
    raw = build_md_package(_MINIMAL_PDB, _MINIMAL_TOP)
    with _open_zip(raw) as zf:
        script = zf.read("md_package/gmx.sh").decode()
    assert "set -e" in script


def test_gmx_sh_has_pdb2gmx_when_peptide():
    raw = build_md_package(
        _MINIMAL_PDB, _MINIMAL_TOP,
        has_peptide=True, peptide_pdb_text=_MINIMAL_PEPTIDE_PDB,
    )
    with _open_zip(raw) as zf:
        script = zf.read("md_package/gmx.sh").decode()
    assert "pdb2gmx" in script


def test_patch_topology_included_with_peptide():
    raw = build_md_package(
        _MINIMAL_PDB, _MINIMAL_TOP,
        has_peptide=True, peptide_pdb_text=_MINIMAL_PEPTIDE_PDB,
    )
    with _open_zip(raw) as zf:
        assert "md_package/patch_topology.py" in zf.namelist()


def test_patch_topology_absent_without_peptide():
    raw = build_md_package(_MINIMAL_PDB, _MINIMAL_TOP)
    with _open_zip(raw) as zf:
        assert "md_package/patch_topology.py" not in zf.namelist()


def test_gmx_sh_has_preflight_check():
    raw = build_md_package(_MINIMAL_PDB, _MINIMAL_TOP)
    with _open_zip(raw) as zf:
        script = zf.read("md_package/gmx.sh").decode()
    assert "command -v gmx" in script


def test_gmx_sh_no_pdb2gmx_without_peptide():
    raw = build_md_package(_MINIMAL_PDB, _MINIMAL_TOP)
    with _open_zip(raw) as zf:
        script = zf.read("md_package/gmx.sh").decode()
    assert "pdb2gmx" not in script


def test_gmx_sh_solvated_skips_editconf_solvate():
    raw = build_md_package(_MINIMAL_PDB, _MINIMAL_TOP, solvated=True)
    with _open_zip(raw) as zf:
        script = zf.read("md_package/gmx.sh").decode()
    assert "gmx solvate" not in script
    assert "gmx genion" not in script


def test_gmx_sh_unsolvated_includes_solvate():
    raw = build_md_package(_MINIMAL_PDB, _MINIMAL_TOP, solvated=False)
    with _open_zip(raw) as zf:
        script = zf.read("md_package/gmx.sh").decode()
    assert "gmx solvate" in script
    assert "gmx genion" in script


def test_readme_mentions_charmm36():
    raw = build_md_package(_MINIMAL_PDB, _MINIMAL_TOP)
    with _open_zip(raw) as zf:
        readme = zf.read("md_package/README.txt").decode()
    assert "charmm36.ff" in readme
    assert "GROMACS" in readme


# ── endpoint tests ────────────────────────────────────────────────────────────

def test_endpoint_returns_zip():
    resp = client.post(
        "/api/md_package",
        data={
            "pdb": _MINIMAL_PDB,
            "topology": _MINIMAL_TOP,
            "has_peptide": "false",
            "peptide_pdb": "",
            "solvated": "false",
        },
    )
    assert resp.status_code == 200
    assert resp.headers["content-type"] == "application/zip"
    assert zipfile.is_zipfile(io.BytesIO(resp.content))


def test_endpoint_content_disposition():
    resp = client.post(
        "/api/md_package",
        data={"pdb": _MINIMAL_PDB, "topology": _MINIMAL_TOP},
    )
    assert "bilbo_md_package.zip" in resp.headers.get("content-disposition", "")


def test_endpoint_with_peptide_includes_peptide_pdb():
    resp = client.post(
        "/api/md_package",
        data={
            "pdb": _MINIMAL_PDB,
            "topology": _MINIMAL_TOP,
            "has_peptide": "true",
            "peptide_pdb": _MINIMAL_PEPTIDE_PDB,
            "solvated": "false",
        },
    )
    assert resp.status_code == 200
    with _open_zip(resp.content) as zf:
        assert "md_package/peptide.pdb" in zf.namelist()
