"""Generate GROMACS topology files for bilayer systems."""

from pathlib import Path

from bilbo.builders.leaflet_layout import LeafletLayout


def _rle(positions) -> list[tuple[str, int]]:
    """Run-length encode a sequence of LipidPositions into (lipid_id, count) pairs."""
    runs: list[tuple[str, int]] = []
    for pos in positions:
        if runs and runs[-1][0] == pos.lipid_id:
            runs[-1] = (runs[-1][0], runs[-1][1] + 1)
        else:
            runs.append((pos.lipid_id, 1))
    return runs


def write_gromacs_topology(
    layouts: dict[str, LeafletLayout],
    output_path: Path,
    ff_dir: str = "charmm36.ff",
    system_name: str = "BILBO Membrane",
) -> list[str]:
    """Write a GROMACS topol.top for the bilayer system.

    Molecule order matches the all-atom PDB produced by write_allatom_preview:
    upper leaflet positions in layout order, then lower leaflet in layout order.
    Adjacent identical lipid types are collapsed into one entry.

    Returns the list of unique lipid residue names included.
    """
    unique_lipids: list[str] = []
    seen: set[str] = set()
    molecule_blocks: list[tuple[str, str, list[tuple[str, int]]]] = []

    for leaflet_name in ("upper", "lower"):
        if leaflet_name not in layouts:
            continue
        runs = _rle(layouts[leaflet_name].positions)
        molecule_blocks.append((leaflet_name, leaflet_name + " leaflet", runs))
        for lipid_id, _ in runs:
            if lipid_id not in seen:
                seen.add(lipid_id)
                unique_lipids.append(lipid_id)

    output_path.parent.mkdir(parents=True, exist_ok=True)

    with output_path.open("w", encoding="utf-8") as fh:
        fh.write("; Topology generated by BILBO\n")
        fh.write(f"; Force field: {ff_dir}\n")
        fh.write(";\n")
        fh.write("; The coordinate file (preview_allatom.pdb) is a structural preview.\n")
        fh.write("; Before running MD: add solvent/ions, energy-minimize, and equilibrate.\n")
        fh.write(";\n\n")

        fh.write(f'#include "{ff_dir}/forcefield.itp"\n\n')

        fh.write("; Lipid molecule topologies\n")
        for lipid_id in unique_lipids:
            fh.write(f'#include "{ff_dir}/{lipid_id}.itp"\n')
        fh.write("\n")

        fh.write("[ system ]\n")
        fh.write(f"{system_name}\n\n")

        fh.write("[ molecules ]\n")
        fh.write("; molecule-type  count\n")
        for leaflet_name, comment, runs in molecule_blocks:
            fh.write(f"; {comment}\n")
            for lipid_id, count in runs:
                fh.write(f"{lipid_id:<15s} {count}\n")

    return unique_lipids
