"""Generate Markdown build report."""

from pathlib import Path

from bilbo.models.build import BuildReport


def write_markdown_report(report: BuildReport, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# BILBO Build Report",
        "",
        "> This report describes a membrane preview generated by BILBO.",
        "> The output files are for visual inspection only and are not suitable for molecular simulation.",
        "",
        "## Build parameters",
        "",
        f"- **Preset**: {report.preset_id}",
        f"- **Force field**: {report.force_field}",
        f"- **Engine**: {report.engine}",
        f"- **Lipids per leaflet**: {report.lipids_per_leaflet}",
        f"- **Sorting mode**: {report.sorting_mode}",
        f"- **Seed**: {report.seed}",
        "",
        "## Desired composition",
        "",
    ]

    for leaflet, comp in report.desired_composition.items():
        lines.append(f"### {leaflet}")
        lines.append("")
        lines.append("| Lipid | % |")
        lines.append("|-------|---|")
        for lid, pct in comp.items():
            lines.append(f"| {lid} | {pct} |")
        lines.append("")

    lines.append("## Realized composition")
    lines.append("")

    for leaflet, comp in report.realized_composition.items():
        lines.append(f"### {leaflet}")
        lines.append("")
        lines.append("| Lipid | Count |")
        lines.append("|-------|-------|")
        for lid, cnt in comp.items():
            lines.append(f"| {lid} | {cnt} |")
        lines.append("")

    if report.warnings:
        lines.append("## Warnings")
        lines.append("")
        for w in report.warnings:
            lines.append(f"- {w}")
        lines.append("")

    if report.errors:
        lines.append("## Errors")
        lines.append("")
        for e in report.errors:
            lines.append(f"- {e}")
        lines.append("")

    if report.generated_files:
        lines.append("## Generated files")
        lines.append("")
        for f in report.generated_files:
            lines.append(f"- `{f}`")
        lines.append("")

    if report.peptide_placements:
        lines.append("## Peptide placements")
        lines.append("")
        for pp in report.peptide_placements:
            lines.append(f"### {pp.placement_id}")
            lines.append("")
            lines.append(f"- **Peptide**: {pp.peptide_id}")
            lines.append(f"- **Orientation**: {pp.orientation}")
            lines.append(f"- **Leaflet**: {pp.leaflet}")
            lines.append(f"- **Collisions**: {pp.collision_count}")
            if pp.minimum_distance_to_membrane is not None:
                lines.append(f"- **Min distance to membrane**: {pp.minimum_distance_to_membrane:.2f} A")
            if pp.warnings:
                for w in pp.warnings:
                    lines.append(f"- Warning: {w}")
            lines.append("")

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
