"""Build a ready-to-run GROMACS MD ZIP package from a BILBO membrane build."""

import io
import re
import zipfile
from pathlib import Path


_TMPL_DIR = Path(__file__).parent / "mdp_templates"
_MDP_FILES = ("em.mdp", "nvt.mdp", "npt.mdp", "prod.mdp")

_LIPID_ITP_DIR = Path(__file__).parent.parent.parent.parent / "data" / "ff" / "charmm36_lipids"


def _read_tmpl(name: str) -> str:
    return (_TMPL_DIR / name).read_text(encoding="utf-8")


def _gmx_sh(has_peptide: bool, solvated: bool) -> str:
    lines = [
        "#!/usr/bin/env bash",
        "# GROMACS MD run script generated by BILBO",
        "# Requirements: GROMACS 2021+ with CHARMM36 force field",
        "#   charmm36.ff/ must be present in the working directory.",
        "#   Download: https://mackerell.umaryland.edu/charmm_ff.shtml",
        "set -euo pipefail",
        "",
        "# ── Pre-flight: verify force field directory ──────────────────────────────────",
        "if [ ! -f charmm36.ff/forcefield.itp ]; then",
        "    echo 'ERROR: charmm36.ff/forcefield.itp not found.'",
        "    echo 'Download CHARMM36 from https://mackerell.umaryland.edu/charmm_ff.shtml'",
        "    echo 'and place charmm36.ff/ in this directory before running.'",
        "    exit 1",
        "fi",
        "",
    ]

    if has_peptide:
        lines += [
            "# ── Step 0: generate protein topology ────────────────────────────────────────",
            "# Extract protein residues from system.pdb (correct membrane-frame coordinates).",
            "python3 - <<'PYEOF'",
            "import pathlib",
            "NON_PROT = {",
            "    'POPE','POPG','POPC','DPPC','DPPE','DPPG','DPPS','BSM','CHOL','SAPI','CL',",
            "    'SOL','TIP3','SOD','CLA','POT','MG','CAL','ZN','NA','K',",
            "}",
            "lines = [ln for ln in pathlib.Path('system.pdb').read_text().splitlines()",
            "         if ln.startswith(('ATOM','HETATM')) and ln[17:21].strip() not in NON_PROT]",
            "pathlib.Path('protein_insitu.pdb').write_text('\\n'.join(lines) + '\\nEND\\n')",
            "PYEOF",
            "",
            "# pdb2gmx generates protein topology and adds H (output in membrane frame).",
            "gmx pdb2gmx \\",
            "    -f protein_insitu.pdb \\",
            "    -o protein_with_h.pdb \\",
            "    -p protein_topol.top \\",
            "    -i posre.itp \\",
            "    -ff charmm36 \\",
            "    -water tip3p \\",
            "    -ignh",
            "",
            "# Extract protein.itp, patch topol.top, rebuild system.pdb with H-enriched protein.",
            "python3 patch_topology.py",
            "",
            "COORD_FILE=system.pdb",
            "",
        ]
    else:
        lines += ["COORD_FILE=system.pdb", ""]

    if not solvated:
        lines += [
            "# ── Step 1: define box ───────────────────────────────────────────────────────",
            "gmx editconf -f $COORD_FILE -o boxed.gro -bt triclinic -d 1.2",
            "",
            "# ── Step 2: solvate ──────────────────────────────────────────────────────────",
            "gmx solvate -cp boxed.gro -cs spc216.gro -o solvated.gro -p topol.top",
            "",
            "# ── Step 3: add ions ─────────────────────────────────────────────────────────",
            "gmx grompp -f em.mdp -c solvated.gro -p topol.top -o ions.tpr -maxwarn 2",
            "echo 'SOL' | gmx genion \\",
            "    -s ions.tpr -o ionized.gro -p topol.top \\",
            "    -pname NA -nname CL -neutral -conc 0.15",
            "",
            "COORD_FILE=ionized.gro",
            "",
        ]
    else:
        lines += [
            "# System is already solvated and ionized by BILBO.",
            "# Convert PDB to GRO for GROMACS.",
            "gmx editconf -f $COORD_FILE -o system.gro",
            "COORD_FILE=system.gro",
            "",
        ]

    lines += [
        "# ── Energy minimization ──────────────────────────────────────────────────────",
        "gmx grompp -f em.mdp -c $COORD_FILE -p topol.top -o em.tpr",
        "gmx mdrun -v -deffnm em",
        "",
        "# ── NVT equilibration ────────────────────────────────────────────────────────",
        "gmx grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr",
        "gmx mdrun -v -deffnm nvt",
        "",
        "# ── NPT equilibration ────────────────────────────────────────────────────────",
        "gmx grompp -f npt.mdp -c nvt.gro -r nvt.gro -t nvt.cpt -p topol.top -o npt.tpr",
        "gmx mdrun -v -deffnm npt",
        "",
        "# ── Production MD ────────────────────────────────────────────────────────────",
        "gmx grompp -f prod.mdp -c npt.gro -t npt.cpt -p topol.top -o prod.tpr",
        "gmx mdrun -v -deffnm prod",
        "",
        "echo 'Done. Trajectory: prod.xtc  Final structure: prod.gro'",
    ]

    return "\n".join(lines) + "\n"


def _readme(has_peptide: bool, solvated: bool) -> str:
    lines = [
        "BILBO MD Package",
        "================",
        "",
        "Requirements",
        "------------",
        "- GROMACS 2021 or newer",
        "- CHARMM36 force field directory (charmm36.ff/) in the working directory",
        "  Download: https://mackerell.umaryland.edu/charmm_ff.shtml",
        "  The lipid ITP files bundled in this package (charmm36.ff/*.itp) supplement",
        "  the base CHARMM36 download and are derived from the CHARMM36 force field",
        "  (MacKerell lab, UMaryland). If you use these parameters in a publication,",
        "  cite: Klauda et al., J. Phys. Chem. B 114:7830 (2010) for lipid parameters.",
        "",
        "Files included",
        "--------------",
        "  system.pdb        : membrane coordinates (and solvent/ions if solvated)",
        "  topol.top         : GROMACS topology (lipids",
    ]

    if has_peptide:
        lines[-1] += ", peptide processed via pdb2gmx)"
        lines += [
            "  peptide.pdb       : isolated peptide/protein coordinates (input to pdb2gmx)",
        ]
    else:
        lines[-1] += ")"

    if solvated:
        lines += ["  topol.top includes water and ion entries (SOL, SOD, CLA)"]

    lines += [
        "  charmm36.ff/*.itp : CHARMM36 lipid topology files for this system",
        "  em.mdp            : energy minimization parameters",
        "  nvt.mdp           : NVT equilibration (100 ps, 310.15 K)",
        "  npt.mdp           : NPT equilibration (100 ps, 310.15 K, semiisotropic P)",
        "  prod.mdp          : production MD (100 ns, 310.15 K, semiisotropic P)",
        "  gmx.sh            : complete GROMACS workflow script",
        "",
        "Usage",
        "-----",
        "  1. Place the base charmm36.ff/ directory here (from mackerell.umaryland.edu).",
        "     The lipid ITP files in charmm36.ff/ from this package are already included.",
    ]

    if has_peptide:
        lines += [
            "  2. gmx.sh runs pdb2gmx on peptide.pdb automatically.",
            "     Review the terminal output to confirm residue assignments.",
        ]
        lines += ["  3. bash gmx.sh"]
    else:
        lines += ["  2. bash gmx.sh"]

    lines += [
        "",
        "Simulation parameters",
        "---------------------",
        "  Temperature : 310.15 K (37 C)",
        "  Pressure    : 1.0 bar, semiisotropic coupling (membrane-appropriate)",
        "  Production  : 100 ns",
        "  Force field : CHARMM36",
        "  Water model : TIP3P",
    ]

    return "\n".join(lines) + "\n"


def _lipid_itps_for_topology(topology_text: str) -> dict[str, bytes]:
    """Return {filename: content} for every lipid ITP referenced in topology_text."""
    includes = re.findall(r'#include\s+"charmm36\.ff/(\w+\.itp)"', topology_text)
    result: dict[str, bytes] = {}
    for fname in includes:
        itp_path = _LIPID_ITP_DIR / fname
        if itp_path.exists():
            result[fname] = itp_path.read_bytes()
    return result


def build_md_package(
    pdb_text: str,
    topology_text: str,
    has_peptide: bool = False,
    peptide_pdb_text: str = "",
    solvated: bool = False,
) -> bytes:
    """Return a ZIP archive (bytes) with all files needed for a GROMACS MD run."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("md_package/system.pdb", pdb_text)
        zf.writestr("md_package/topol.top", topology_text)

        if has_peptide and peptide_pdb_text:
            zf.writestr("md_package/peptide.pdb", peptide_pdb_text)

        for mdp in _MDP_FILES:
            zf.writestr(f"md_package/{mdp}", _read_tmpl(mdp))

        if has_peptide:
            zf.writestr("md_package/patch_topology.py", _read_tmpl("patch_topology.py"))

        for fname, content in _lipid_itps_for_topology(topology_text).items():
            zf.writestr(f"md_package/charmm36.ff/{fname}", content)

        zf.writestr("md_package/gmx.sh", _gmx_sh(has_peptide, solvated))
        zf.writestr("md_package/README.txt", _readme(has_peptide, solvated))

    return buf.getvalue()
