"""Build a ready-to-run GROMACS MD ZIP package from a BILBO membrane build."""

import io
import os
import re
import zipfile
from pathlib import Path


_TMPL_DIR = Path(__file__).parent / "mdp_templates"
_MDP_FILES = ("em.mdp", "nvt.mdp", "npt.mdp", "prod.mdp")

# BILBO_DATA_DIR can be set to the project root when the package is installed
# in non-editable mode (e.g. production Docker), where Path(__file__) resolves
# inside site-packages rather than the project tree.
_PROJECT_ROOT = Path(os.environ.get("BILBO_DATA_DIR", Path(__file__).parent.parent.parent.parent))
_FF_DATA_DIR = _PROJECT_ROOT / "data" / "ff"
_LIPID_ITP_DIR = _FF_DATA_DIR / "charmm36_lipids"
_FF_BASE_DIR = _FF_DATA_DIR / "charmm36_base"


def _read_tmpl(name: str) -> str:
    return (_TMPL_DIR / name).read_text(encoding="utf-8")


def _gmx_sh(has_peptide: bool, solvated: bool) -> str:
    lines = [
        "#!/usr/bin/env bash",
        "# GROMACS MD run script generated by BILBO",
        "# Requirements: GROMACS 2021+",
        "# The charmm36.ff/ directory is bundled in this package.",
        "set -euo pipefail",
        "",
        "# ── Pre-flight: verify GROMACS is available ───────────────────────────────────",
        "if ! command -v gmx &>/dev/null; then",
        "    echo 'ERROR: gmx not found. Install GROMACS 2021+ and add it to PATH.'",
        "    exit 1",
        "fi",
        "",
    ]

    if has_peptide:
        lines += [
            "# ── Step 0: generate protein topology ────────────────────────────────────────",
            "# Extract protein residues from system.pdb (correct membrane-frame coordinates).",
            "python3 - <<'PYEOF'",
            "import pathlib",
            "NON_PROT = {",
            "    'POPE','POPG','POPC','DPPC','DPPE','DPPG','DPPS','POPS','BSM','CHOL','SAPI','CL',",
            "    'SOL','TIP3','SOD','CLA','POT','MG','CAL','ZN','NA','K',",
            "}",
            "lines = [ln for ln in pathlib.Path('system.pdb').read_text().splitlines()",
            "         if ln.startswith(('ATOM','HETATM')) and ln[17:21].strip() not in NON_PROT]",
            "pathlib.Path('protein_insitu.pdb').write_text('\\n'.join(lines) + '\\nEND\\n')",
            "PYEOF",
            "",
            "# pdb2gmx generates protein topology and adds H (output in membrane frame).",
            "gmx pdb2gmx \\",
            "    -f protein_insitu.pdb \\",
            "    -o protein_with_h.pdb \\",
            "    -p protein_topol.top \\",
            "    -i posre.itp \\",
            "    -ff charmm36 \\",
            "    -water tip3p \\",
            "    -ignh",
            "",
            "# Extract protein.itp, patch topol.top, rebuild system.pdb with H-enriched protein.",
            "python3 patch_topology.py",
            "",
            "COORD_FILE=system.pdb",
            "",
        ]
    else:
        lines += ["COORD_FILE=system.pdb", ""]

    if not solvated:
        lines += [
            "# ── Step 1: define box ───────────────────────────────────────────────────────",
            "gmx editconf -f $COORD_FILE -o boxed.gro -bt triclinic -d 1.2",
            "",
            "# ── Step 2: solvate ──────────────────────────────────────────────────────────",
            "gmx solvate -cp boxed.gro -cs spc216.gro -o solvated.gro -p topol.top",
            "",
            "# ── Step 3: add ions ─────────────────────────────────────────────────────────",
            "gmx grompp -f em.mdp -c solvated.gro -p topol.top -o ions.tpr -maxwarn 2",
            "echo 'SOL' | gmx genion \\",
            "    -s ions.tpr -o ionized.gro -p topol.top \\",
            "    -pname NA -nname CL -neutral -conc 0.15",
            "",
            "COORD_FILE=ionized.gro",
            "",
        ]
    else:
        lines += [
            "# System is already solvated and ionized by BILBO.",
            "# Convert PDB to GRO for GROMACS.",
            "gmx editconf -f $COORD_FILE -o system.gro",
            "COORD_FILE=system.gro",
            "",
        ]

    lines += [
        "# ── Energy minimization ──────────────────────────────────────────────────────",
        "gmx grompp -f em.mdp -c $COORD_FILE -p topol.top -o em.tpr",
        "gmx mdrun -v -deffnm em",
        "",
        "# ── NVT equilibration ────────────────────────────────────────────────────────",
        "gmx grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr",
        "gmx mdrun -v -deffnm nvt",
        "",
        "# ── NPT equilibration ────────────────────────────────────────────────────────",
        "gmx grompp -f npt.mdp -c nvt.gro -r nvt.gro -t nvt.cpt -p topol.top -o npt.tpr",
        "gmx mdrun -v -deffnm npt",
        "",
        "# ── Production MD ────────────────────────────────────────────────────────────",
        "gmx grompp -f prod.mdp -c npt.gro -t npt.cpt -p topol.top -o prod.tpr",
        "gmx mdrun -v -deffnm prod",
        "",
        "echo 'Done. Trajectory: prod.xtc  Final structure: prod.gro'",
    ]

    return "\n".join(lines) + "\n"


def _readme(has_peptide: bool, solvated: bool, bundle_ff: bool = True) -> str:
    if bundle_ff:
        ff_req = "- No additional downloads required. The charmm36.ff/ directory is bundled."
    else:
        ff_req = (
            "- Download the full MD package from the BILBO web interface to get the\n"
            "  bundled charmm36.ff/ directory, or provide your own CHARMM36 installation.\n"
            "  This email version does NOT include the force field files."
        )

    lines = [
        "BILBO MD Package",
        "================",
        "",
        "Requirements",
        "------------",
        "- GROMACS 2021 or newer (gmx must be in PATH)",
        ff_req,
        "",
        "Force field attribution",
        "-----------------------",
        "If you publish results from these simulations, cite:",
        "  Klauda et al., J. Phys. Chem. B 114:7830 (2010)  -- lipid parameters",
        "  Best et al., JCTC 8:3257 (2012)                  -- protein parameters",
        "",
        "Files included",
        "--------------",
        "  system.pdb        : membrane coordinates (and solvent/ions if solvated)",
        "  topol.top         : GROMACS topology (lipids",
    ]

    if has_peptide:
        lines[-1] += ", peptide processed via pdb2gmx)"
        lines += [
            "  peptide.pdb       : isolated peptide/protein coordinates (input to pdb2gmx)",
        ]
    else:
        lines[-1] += ")"

    if solvated:
        lines += ["  topol.top includes water and ion entries (SOL, SOD, CLA)"]

    if bundle_ff:
        lines += ["  charmm36.ff/      : complete CHARMM36 force field (Feb 2026, CGenFF 5.0)"]

    lines += [
        "  em.mdp            : energy minimization parameters",
        "  nvt.mdp           : NVT equilibration (100 ps, 310.15 K)",
        "  npt.mdp           : NPT equilibration (100 ps, 310.15 K, semiisotropic P)",
        "  prod.mdp          : production MD (100 ns, 310.15 K, semiisotropic P)",
        "  gmx.sh            : complete GROMACS workflow script",
        "",
        "Usage",
        "-----",
    ]

    if has_peptide:
        lines += [
            "  1. gmx.sh runs pdb2gmx on peptide.pdb automatically.",
            "     Review the terminal output to confirm residue assignments.",
            "  2. bash gmx.sh",
        ]
    else:
        lines += ["  1. bash gmx.sh"]

    lines += [
        "",
        "Simulation parameters",
        "---------------------",
        "  Temperature : 310.15 K (37 C)",
        "  Pressure    : 1.0 bar, semiisotropic coupling (membrane-appropriate)",
        "  Production  : 100 ns",
        "  Force field : CHARMM36",
        "  Water model : TIP3P",
    ]

    return "\n".join(lines) + "\n"


def _bundle_ff(zf: zipfile.ZipFile) -> None:
    """Write the complete charmm36.ff/ into the ZIP: base files + all lipid ITPs."""
    for src_dir in (_FF_BASE_DIR, _LIPID_ITP_DIR):
        if not src_dir.exists():
            continue
        for f in sorted(src_dir.iterdir()):
            if f.is_file() and not f.name.startswith("."):
                zf.writestr(f"md_package/charmm36.ff/{f.name}", f.read_bytes())


_DT = 0.002  # ps


def _sub(text: str, key: str, value: str, comment: str = "") -> str:
    suffix = f"  ; {comment}" if comment else ""
    return re.sub(rf'{key}\s*=\s*[^\n]+', f'{key:<16s}= {value}{suffix}', text)


def _nvt_mdp(equil_ps: float, temp_k: float, output_freq_ps: float) -> str:
    nsteps = int(equil_ps / _DT)
    out_steps = max(1, int(output_freq_ps / _DT))
    text = _read_tmpl("nvt.mdp")
    text = re.sub(r'nsteps\s*=\s*\d+[^\n]*', f'nsteps          = {nsteps:<14d}; {equil_ps:g} ps', text)
    for key in ("nstxout", "nstvout", "nstenergy", "nstlog"):
        text = _sub(text, key, str(out_steps))
    text = _sub(text, "ref_t", f"{temp_k:.2f}")
    text = _sub(text, "gen_temp", f"{temp_k:.2f}")
    return text


def _npt_mdp(equil_ps: float, temp_k: float, output_freq_ps: float) -> str:
    nsteps = int(equil_ps / _DT)
    out_steps = max(1, int(output_freq_ps / _DT))
    text = _read_tmpl("npt.mdp")
    text = re.sub(r'nsteps\s*=\s*\d+[^\n]*', f'nsteps          = {nsteps:<14d}; {equil_ps:g} ps', text)
    for key in ("nstxout", "nstvout", "nstenergy", "nstlog"):
        text = _sub(text, key, str(out_steps))
    text = _sub(text, "ref_t", f"{temp_k:.2f}")
    return text


def _prod_mdp(traj_ns: float, temp_k: float, output_freq_ps: float) -> str:
    nsteps = int(traj_ns * 1_000 / _DT)
    out_steps = max(1, int(output_freq_ps / _DT))
    text = _read_tmpl("prod.mdp")
    text = re.sub(r'nsteps\s*=\s*\d+[^\n]*', f'nsteps          = {nsteps:<14d}; {traj_ns:g} ns', text)
    text = re.sub(r'; \d[\d.]* ns at ', f'; {traj_ns:g} ns at ', text)
    for key in ("nstxout-compressed", "nstenergy", "nstlog"):
        text = _sub(text, key, str(out_steps))
    text = _sub(text, "ref_t", f"{temp_k:.2f}")
    return text


def build_md_package(
    pdb_text: str,
    topology_text: str,
    has_peptide: bool = False,
    peptide_pdb_text: str = "",
    solvated: bool = False,
    traj_ns: float = 100.0,
    temp_k: float = 310.15,
    equil_ps: float = 100.0,
    output_freq_ps: float = 10.0,
    bundle_ff: bool = True,
) -> bytes:
    """Return a ZIP archive (bytes) with all files needed for a GROMACS MD run.

    Set bundle_ff=False to omit the charmm36.ff/ directory (e.g. for email
    attachments where size is constrained; users must supply the FF separately).
    """
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("md_package/system.pdb", pdb_text)
        zf.writestr("md_package/topol.top", topology_text)

        if has_peptide and peptide_pdb_text:
            zf.writestr("md_package/peptide.pdb", peptide_pdb_text)

        _mdp_map = {
            "em.mdp": lambda: _read_tmpl("em.mdp"),
            "nvt.mdp": lambda: _nvt_mdp(equil_ps, temp_k, output_freq_ps),
            "npt.mdp": lambda: _npt_mdp(equil_ps, temp_k, output_freq_ps),
            "prod.mdp": lambda: _prod_mdp(traj_ns, temp_k, output_freq_ps),
        }
        for mdp in _MDP_FILES:
            zf.writestr(f"md_package/{mdp}", _mdp_map[mdp]())

        if has_peptide:
            zf.writestr("md_package/patch_topology.py", _read_tmpl("patch_topology.py"))

        if bundle_ff:
            _bundle_ff(zf)

        zf.writestr("md_package/gmx.sh", _gmx_sh(has_peptide, solvated))
        zf.writestr("md_package/README.txt", _readme(has_peptide, solvated, bundle_ff=bundle_ff))

    return buf.getvalue()
