"""Generate PyMOL visualization script."""

from pathlib import Path


def write_pymol_script(
    output_path: Path,
    pdb_filename: str = "preview.pdb",
    lipid_ids: list[str] | None = None,
    has_peptide: bool = False,
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by BILBO for visual inspection only.",
        "# Not suitable for molecular simulation.",
        f"load {pdb_filename}, bilbo_membrane",
        "hide everything, bilbo_membrane",
        "show spheres, bilbo_membrane",
        "set sphere_scale, 0.55, bilbo_membrane",
        "set orthoscopic, on",
        "bg_color white",
        "select upper_leaflet, chain U",
        "select lower_leaflet, chain L",
        "color marine, upper_leaflet",
        "color orange, lower_leaflet",
    ]

    if lipid_ids:
        for lid in lipid_ids:
            safe_id = lid.replace("-", "_")
            resname = lid[:4] if len(lid) > 4 else lid
            lines.append(f"select {safe_id}, resn {resname}")

    if has_peptide:
        lines += [
            "select peptide_chain, chain P",
            "show sticks, peptide_chain",
            "color tv_green, peptide_chain",
        ]

    lines.append("zoom bilbo_membrane")

    with output_path.open("w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
