"""Generate VMD visualization script."""

from pathlib import Path


def write_vmd_script(
    output_path: Path,
    pdb_filename: str = "preview.pdb",
    lipid_ids: list[str] | None = None,
    has_peptide: bool = False,
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by BILBO for visual inspection only.",
        "# Not suitable for molecular simulation.",
        f"mol new {pdb_filename} type pdb",
        "mol delrep 0 top",
        "mol representation VDW 0.8 12",
        "mol color ResName",
        "mol selection all",
        "mol addrep top",
        "display projection Orthographic",
        "axes location Off",
        "color Display Background white",
        "",
        "mol representation VDW 1.0 12",
        "mol color ColorID 0",
        "mol selection chain U",
        "mol addrep top",
        "",
        "mol representation VDW 1.0 12",
        "mol color ColorID 1",
        "mol selection chain L",
        "mol addrep top",
    ]

    if has_peptide:
        lines += [
            "",
            "mol representation NewCartoon",
            "mol color ColorID 4",
            "mol selection chain P",
            "mol addrep top",
        ]

    with output_path.open("w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
